apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
spec:
  capacity:
    storage: 6Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain  # Set ReclaimPolicy to Retain to prevent deletion of data
  storageClassName: hostpath
  hostPath:
    path: "/mnt/data/jenkins"  # Path on your host where the data will be stored